/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dasd_stemcell_OSXApplication */
 
#ifndef _Included_org_dasd_stemcell_OSXApplication
#define _Included_org_dasd_stemcell_OSXApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dasd_stemcell_OSXApplication
 * Method:    toFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dasd_stemcell_OSXApplication_toFront
  (JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif